"""Removal of video link from landmark table

Revision ID: 05517930be26
Revises: c6ecc0f1bbb7
Create Date: 2022-06-25 09:00:45.333553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05517930be26'
down_revision = 'c6ecc0f1bbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_data', 'video_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_data', sa.Column('video_link', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
