"""Increase groups name string

Revision ID: 18d605773229
Revises: 5ddd1268e3a9
Create Date: 2022-06-22 07:18:55.927703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d605773229'
down_revision = '5ddd1268e3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_update', sa.Boolean(), nullable=False))
    op.drop_column('users', 'strava_fetch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_fetch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'strava_update')
    # ### end Alembic commands ###
