"""Connection date remove nullable

Revision ID: 245e4212262a
Revises: 
Create Date: 2022-06-08 19:47:53.557896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245e4212262a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'connection_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'connection_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
