"""Remove unwanted colums & notifcations table

Revision ID: 54f39a4fa5a7
Revises: 05517930be26
Create Date: 2022-06-25 09:56:25.084809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f39a4fa5a7'
down_revision = '05517930be26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_column('map_data', 'video_link')
    op.drop_constraint('users_icon_url_key', 'users', type_='unique')
    op.drop_constraint('users_refresh_token_key', 'users', type_='unique')
    op.drop_column('users', 'connection_date')
    op.drop_column('users', 'strava_fetch')
    op.drop_column('users', 'strava_last_activity_id')
    op.drop_column('users', 'icon_url')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'connection_status')
    op.drop_column('users', 'update_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('connection_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('icon_url', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('strava_last_activity_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('strava_fetch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('connection_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_refresh_token_key', 'users', ['refresh_token'])
    op.create_unique_constraint('users_icon_url_key', 'users', ['icon_url'])
    op.add_column('map_data', sa.Column('video_link', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_table('notifications',
    sa.Column('notifcation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('marked_as_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notifcation_id', name='notifications_pkey')
    )
    # ### end Alembic commands ###
