"""Adding icon_num to user table

Revision ID: 5ddd1268e3a9
Revises: e2d0fcf1c3e5
Create Date: 2022-06-13 21:10:52.181690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd1268e3a9'
down_revision = 'e2d0fcf1c3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon_num')
    # ### end Alembic commands ###
