"""remove group name from users

Revision ID: c6ecc0f1bbb7
Revises: 18d605773229
Create Date: 2022-06-22 07:37:27.006339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ecc0f1bbb7'
down_revision = '18d605773229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_name', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
