"""remove require unique constraint

Revision ID: e2d0fcf1c3e5
Revises: 245e4212262a
Create Date: 2022-06-08 20:04:08.063556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d0fcf1c3e5'
down_revision = '245e4212262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_strava_last_activity_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_strava_last_activity_id_key', 'users', ['strava_last_activity_id'])
    # ### end Alembic commands ###
